# Generated by Django 3.2.6 on 2023-09-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230904_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label',
            new_name='label_name',
        ),
    ]
