# Generated by Django 3.2.6 on 2023-09-07 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_label_name_label_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mainlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_loacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sublocation')),
            ],
        ),
    ]
