# Generated by Django 3.2.6 on 2023-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_department_mainlocation_sublocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField()),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('po_number', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('main_location', models.CharField(max_length=255)),
                ('sub_location', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(max_length=255)),
                ('asset_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('channel', models.CharField(max_length=50)),
                ('custodian', models.CharField(max_length=255)),
                ('holder_name', models.CharField(max_length=255)),
            ],
        ),
    ]
