# Generated by Django 3.2.6 on 2023-09-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_asset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
        migrations.RenameModel(
            old_name='MainLocation',
            new_name='Main_Location',
        ),
        migrations.RenameModel(
            old_name='SubLocation',
            new_name='Sub_Location',
        ),
    ]
