# Generated by Django 3.2.6 on 2023-09-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230908_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_location',
            name='main_location',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Main_Location',
        ),
        migrations.DeleteModel(
            name='Sub_Location',
        ),
    ]
