# Generated by Django 3.2.6 on 2023-09-12 04:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_department_mainlocation_sublocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='department',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='holder_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='main_location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sub_location',
        ),
        migrations.AddField(
            model_name='asset',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ReturnedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(max_length=255)),
                ('custodian', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('returned', 'Returned'), ('in_possession', 'In Possession')], default='in_possession', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.asset')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
    ]
