# Generated by Django 3.2.6 on 2023-09-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230912_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
