# Generated by Django 3.2.6 on 2023-09-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230919_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bar_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
