# Generated by Django 3.2.6 on 2023-10-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_asset_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='bar_code',
            field=models.CharField(max_length=100),
        ),
    ]
