# Generated by Django 5.0.6 on 2024-07-22 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_category_remove_assetassignment_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('image', 'Image'), ('pdf', 'PDF')], max_length=10),
        ),
    ]
