# Generated by Django 5.0.6 on 2024-07-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_title_document_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentassignment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='documentassignment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='documentassignment',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DocumentAssignment',
        ),
    ]
