# Generated by Django 5.0.6 on 2024-07-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_id_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission_level',
            field=models.CharField(choices=[('read_write', 'Read and Write'), ('read_only', 'Read Only')], default='read_only', max_length=10),
        ),
    ]
