# Generated by Django 5.0.6 on 2024-07-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_permission_level_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='permission_level',
        # ),
    ]
